version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd yagami && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true